name: flutter_assistview_getting_started
description: "This Flutter project contains getting started samples of Syncfusion AI AssistView widget."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_core: ^28.1.33
  syncfusion_flutter_chat: ^28.1.33-beta
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

